### ISSUE TITLE
InvalidArgumentException with guzzlehttp dependency

### ISSUE THREAD

**Issue by sookoll** [googleapis/gax-php#225] opened 2019-01-23 13:48 UTC
Error message is clear:
```
InvalidArgumentException: Passing in the "body" request option as an array to send a POST request has been deprecated. Please use the "form_params" request option to send a application/x-www-form-urlencoded request, or the "multipart" request option to send a multipart/form-data request.
```
Please update library.

**Comment by michaelbausor** [comment] 2019-01-23 18:41
Hi @sookoll, thanks for the bug report. I just tried using the latest gax-php to make API calls with the guzzlehttp/guzzle package installed at multiple different versions (6.3, 6.2, 6.1, 6.0, 5.3), but wasn't able to reproduce the error you're seeing. Can you share a composer.json and an example API call that I can use to reproduce the error? Or else describe how I can reproduce?

**Comment by sookoll** [comment] 2019-01-23 22:17
ah, it might that I was wrong about which package made this error. Several google api packages are using guzzle through different api libraries, so it is hard to tweak it out.

Anyway, composer.json:
```
{
    "config": {
        "vendor-dir": "src/vendor"
    },
    "require": {
        "silex/silex": "~1.3",
        "twig/twig": ">=1.8,<2.0-dev",
        "monolog/monolog": ">=1.18.0",
        "google/photos-library": "^1.1"
    }
}
```
And error occur when I try to upload photo:
```
$photosLibraryClient = new PhotosLibraryClient(['credentials' => $this->app['session']->get('googleCredentials')]);
$batchCreateResponse = $photosLibraryClient->batchCreateMediaItems($newMediaItems, ['albumId' => $albumId]);
```

**Comment by michaelbausor** [comment] 2019-01-24 21:02
Hmm, I'm still not able to reproduce the error. I created a sample project with the following structure:.
 - google_photos_logo.png
 - composer.json
 - src/photos.php

The composer.json file is the one you shared. The src/photos.php file is as follows:
```php
<?php

require __DIR__ . '/../src/vendor/autoload.php';

use \Google\Photos\Library\V1\PhotosLibraryClient;
use \Google\Photos\Library\V1\PhotosLibraryResourceFactory;

$photosLibraryClient = new PhotosLibraryClient();

$newAlbum = PhotosLibraryResourceFactory::album("My Album");
$createdAlbum = $photosLibraryClient->createAlbum($newAlbum);
$albumId = $createdAlbum->getId();
echo "Album id: " . $albumId . PHP_EOL;

$localFilePath = __DIR__ . '/../google_photos_logo.png';
$filename = 'google_photos_logo.png';

$uploadToken = $photosLibraryClient->upload(file_get_contents($localFilePath), $filename);
echo "Upload token: " . $uploadToken . PHP_EOL;

$item = PhotosLibraryResourceFactory::newMediaItemWithDescription($uploadToken, "some description");
$newMediaItems = [$item];
$batchCreateResponse = $photosLibraryClient->batchCreateMediaItems($newMediaItems, ['albumId' => $albumId]);

$uploadStatus = $batchCreateResponse->getNewMediaItemResults()[0]->getStatus();

echo "Create response: [" . $uploadStatus->getCode() . "] - " . $uploadStatus->getMessage() . PHP_EOL;
```

I found that this worked successfully. Can you try this sample to see if you still see the error?

**Comment by dwsupplee** [comment] 2019-01-24 21:23
It looks like [`Google/Photos/Library/V1/PhotosLibraryClient.php#L146`](https://github.com/google/php-photoslibrary/blob/7d44b3f34b0f51c8a012d5702661f7d4e758fb7c/src/Google/Photos/Library/V1/PhotosLibraryClient.php#L146) may be what is [triggering the deprecation notice](https://github.com/guzzle/guzzle/blob/a759c5621240718a18813fb6b2bf4621195bb57f/src/Client.php#L118-L120).

@sookoll, do you have any code which is calling `PhotosLibraryClient::upload()` and is passing in an array? The `rawFile` argument is being passed right through to Guzzle's body request option which only accepts [`string|resource|Psr\Http\Message\StreamInterface`](http://docs.guzzlephp.org/en/stable/request-options.html#body).

**Comment by dwsupplee** [comment] 2019-01-25 01:40
What does `curl_download` return? Make sure at the very least it is one of the types accepted by guzzle, and more ideally it should be a string as that is what the public contract for `PhotosLibraryClient::upload()` currently accepts.

**Comment by michaelbausor** [comment] 2019-02-04 16:50
@sookoll It looks like the problem is identified, so I'm going to close this out for now. If you want to reopen to further discuss, please do!

**Closed by michaelbausor** 2019-02-04 16:50 UTC
Labels: type: question
